apiVersion: v2
name: axelor-open-suite
description: |
  Open source ERP and BPM platform.
  Axelor Open Suite reduces the complexity and improve responsiveness of business processes. 
  Thanks to its modularity, you can start with few features and then activate other modules when needed.

type: application

version: 7.2.0
appVersion: "v7.2.0"

home: https://axelor.com/
icon: https://axelor.com/wp-content/uploads/2023/05/logo-axelor-bleu.svg

sources:
  - https://github.com/axelor/axelor-open-suite
  - https://github.com/pmoscode-helm/axelor-open-suite
  - https://github.com/pmoscode-helm/axelor-open-suite-docker

maintainers:
  - name: pmoscode
    url: pmoscode.de
    email: info@pmoscode.de

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.8.0
    condition: postgresql.enabled

annotations:
  artifacthub.io/images: |
    - name: Axelor Open Suite
      image: pmoscode/axelor-open-suite:v7.2.0
      platforms:
        - linux/amd64
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/pmoscode-helm/axelor-open-suite
    - name: support
      url: https://github.com/pmoscode-helm/axelor-open-suite/issues
  artifacthub.io/maintainers: |
    - name: pmoscode
      email: info@pmoscode.de
