apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axelor-open-suite.fullname" . }}
  labels:
    {{- include "axelor-open-suite.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "axelor-open-suite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "axelor-open-suite.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "axelor-open-suite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "axelor-open-suite.fullname" . }}
          env:
            - name: AXELOR_CONFIG_DB_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-postgresql
          volumeMounts:
            - name: {{ include "axelor-open-suite.fullname" . }}-data
              subPath: attachments
              mountPath: /home/axelor/.axelor/attachments
            - name: {{ include "axelor-open-suite.fullname" . }}-data
              subPath: export
              mountPath: /home/axelor/.axelor/export
{{/*            - name: {{ include "axelor-open-suite.fullname" . }}-data*/}}
{{/*              subPath: tomcat*/}}
{{/*              mountPath: /usr/local/tomcat/webapps*/}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 50
            timeoutSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 4
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "axelor-open-suite.fullname" . }}-data
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
          persistentVolumeClaim:
            claimName: {{ include "axelor-open-suite.fullname" . }}-data
          {{- else }}
          emptyDir: { }
          {{- end }}
