apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axelor-open-suite.fullname" . }}-tomcat
  labels:
    {{- include "axelor-open-suite.labels" . | nindent 4 }}
type: Opaque
data:
  tomcat-password: {{ randAlphaNum 10 | b64enc | quote }}
